name: Continuous Itergration and Deployment

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up .NET 6
              uses: actions/setup-dotnet@v3  
              with:
                dotnet-version: '6.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build app
              run: dotnet build -c Release  --no-restore

            - name: Publish app
              run: dotnet publish -c Release -o ./out

            - name: Deploy to Azure Service
              uses: azure/webapps-deploy@v2
              with:
                app-name: toiec-web
                publish-profile: ${{ secrets.TOIEC_WEB_B149 }}
                package: ./out